"""Read out/v9/summary.tsv (and out/v9/summary_3x3.tsv) and emit LaTeX
tabular code for all tables in the v12 manuscript.

Tables produced:
  out/TABLE_v9_size2_djns.tex      — size-2 dj-vs-ns
  out/TABLE_v9_size2_three.tex     — size-2 three-class (no n_*)
  out/TABLE_v9_size2x3_djns.tex    — size-2x3 dj-vs-ns
  out/TABLE_v9_size2x3_three.tex   — size-2x3 three-class (no n_*)
  out/TABLE_v9_size3x3_main.tex    — size-3x3 dj vs ns_1 vs ns_2
  out/TABLE_v9_size3x3_fine.tex    — size-3x3 5-class fine breakdown
"""

import csv
import math
import os

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..")
SUM = os.path.join(ROOT, "out", "v9", "summary.tsv")
SUM_3X3 = os.path.join(ROOT, "out", "v9", "summary_3x3.tsv")

ORDER = [
    "ia-reality-call", "copenhagen-calls",
    "college-msg",
    "friends-family-call", "social-evolution-call",
    "contact-high-school", "contact-primary-school", "DAWN",
    "NDC-classes", "NDC-substances",
    "coauth-DBLP", "coauth-MAG-Geology", "coauth-MAG-History",
    "congress-bills", "email-Enron", "email-Eu",
    "tags-ask-ubuntu", "tags-math-sx", "tags-stack-overflow",
    "threads-ask-ubuntu", "threads-math-sx", "threads-stack-overflow",
]
ORDER_IDX = {n: i for i, n in enumerate(ORDER)}


def fmt_int(s):
    if s in (None, "", "nan"): return "--"
    n = int(float(s))
    return f"{n:,}"


def fmt_f(s, prec=4):
    """Negative values are wrapped in math mode per v12 spec."""
    if s in (None, "", "nan"): return "--"
    try:
        x = float(s)
    except ValueError:
        return "--"
    if x != x:
        return "--"
    out = f"{x:.{prec}f}"
    return f"${out}$" if x < 0 else out


def fmt_p(s):
    if s in (None, "", "nan"): return "--"
    try:
        x = float(s)
    except ValueError:
        return "--"
    if x != x:
        return "--"
    if x < 1e-8:
        return "$<10^{-8}$"
    if x < 1e-3:
        m, e = f"{x:.1e}".split("e")
        return f"${m}\\times 10^{{{int(e)}}}$"
    return f"{x:.3f}"


def load(path):
    rows = []
    with open(path) as fh:
        for r in csv.DictReader(fh, delimiter="\t"):
            rows.append(r)
    rows.sort(key=lambda r: ORDER_IDX.get(r["dataset"], 999))
    return rows


def load_summary():
    rows_by_pt = {"2x2": [], "2x3": []}
    for r in load(SUM):
        pt = r["pair_type"]
        if pt in rows_by_pt:
            rows_by_pt[pt].append(r)
    return rows_by_pt


# Filters
DJ_NS_THRESH = 20    # n_dj >= 20 AND n_ns >= 20
THREE_OPEN_TRI = 10  # n_open >= 10 AND n_tri >= 10 (n_dj uses DJ_NS_THRESH)


def survives_djns(r):
    if int(r["n_dj"]) < DJ_NS_THRESH or int(r["n_ns"]) < DJ_NS_THRESH:
        return False
    e_freq = r.get("E_freq")
    if e_freq not in (None, "", "nan") and int(e_freq) < 50:
        return False
    return True


def survives_three(r):
    if not (int(r["n_dj"]) >= DJ_NS_THRESH and
            int(r["n_open"]) >= THREE_OPEN_TRI and
            int(r["n_tri"]) >= THREE_OPEN_TRI):
        return False
    e_freq = r.get("E_freq")
    if e_freq not in (None, "", "nan") and int(e_freq) < 50:
        return False
    return True


def survives_3x3_main(r):
    return (int(r["n_dj"]) >= DJ_NS_THRESH and
            int(r["n_ns1"]) >= DJ_NS_THRESH and
            int(r["n_ns2"]) >= DJ_NS_THRESH)


def survives_3x3_fine(r):
    return (int(r["n_dj"]) >= DJ_NS_THRESH and
            int(r["n_ns1_open"]) >= THREE_OPEN_TRI and
            int(r["n_ns1_tri"]) >= THREE_OPEN_TRI and
            int(r["n_ns2_open"]) >= THREE_OPEN_TRI and
            int(r["n_ns2_tri"]) >= THREE_OPEN_TRI)


def derive_E_from_pairs_2x2(n_dj, n_ns, n_sh2):
    n_pairs = n_dj + n_ns + n_sh2
    if n_pairs == 0:
        return 0
    return int(round((1 + math.sqrt(1 + 8 * n_pairs)) / 2))


def main():
    rows = load_summary()
    for r in rows["2x2"]:
        r["E_freq"] = str(derive_E_from_pairs_2x2(
            int(r["n_dj"]), int(r["n_ns"]), int(r["n_sh2"])
        ))

    write_djns_size2(rows["2x2"], "TABLE_v9_size2_djns.tex")
    write_three_minimal(rows["2x2"], "TABLE_v9_size2_three.tex")
    write_djns_minimal(rows["2x3"], "TABLE_v9_size2x3_djns.tex")
    write_three_minimal(rows["2x3"], "TABLE_v9_size2x3_three.tex")
    write_size2_merged(rows["2x2"], "TABLE_v9_size2_merged.tex")
    write_size2x3_merged(rows["2x3"], "TABLE_v9_size2x3_merged.tex")

    rows_3x3 = load(SUM_3X3) if os.path.exists(SUM_3X3) else []
    write_3x3_main(rows_3x3, "TABLE_v9_size3x3_main.tex")
    write_3x3_fine(rows_3x3, "TABLE_v9_size3x3_fine.tex")


def write_djns_size2(rows, out_name):
    keep = [r for r in rows if survives_djns(r)]
    out = os.path.join(ROOT, "out", out_name)
    with open(out, "w") as fh:
        fh.write("% generated by code/render_tables_v9.py\n")
        fh.write("\\begin{tabular}{l r r r r r r r}\n\\hline\n")
        fh.write(
            "Dataset & $\\Delta$ & $E_{\\rm freq}$ & "
            "$n_{\\rm dj}$ & $n_{\\rm int}$ & "
            "$\\mu_{\\rm dj}$ & $\\mu_{\\rm int}$ & $d$ \\\\\n\\hline\n"
        )
        for r in keep:
            fh.write(
                f"\\texttt{{{r['dataset']}}} & {r['delta']} & "
                f"{fmt_int(r.get('E_freq', '0'))} & "
                f"{fmt_int(r['n_dj'])} & {fmt_int(r['n_ns'])} & "
                f"{fmt_f(r['mean_dj'])} & {fmt_f(r['mean_ns'])} & "
                f"{fmt_f(r['d_dj_ns'], prec=2)} \\\\\n"
            )
        fh.write("\\hline\n\\end{tabular}\n")
    print(f"Wrote {out}")


def write_djns_minimal(rows, out_name):
    keep = [r for r in rows if survives_djns(r)]
    out = os.path.join(ROOT, "out", out_name)
    with open(out, "w") as fh:
        fh.write("% generated by code/render_tables_v9.py\n")
        fh.write("\\begin{tabular}{l r r r}\n\\hline\n")
        fh.write(
            "Dataset & $\\mu_{\\rm dj}$ & $\\mu_{\\rm int}$ & $d$ "
            "\\\\\n\\hline\n"
        )
        for r in keep:
            fh.write(
                f"\\texttt{{{r['dataset']}}} & "
                f"{fmt_f(r['mean_dj'])} & {fmt_f(r['mean_ns'])} & "
                f"{fmt_f(r['d_dj_ns'], prec=2)} \\\\\n"
            )
        fh.write("\\hline\n\\end{tabular}\n")
    print(f"Wrote {out}")


def write_three_minimal(rows, out_name):
    """Three-class table, no sample-size columns (per v12 spec)."""
    keep = [r for r in rows if survives_three(r)]
    out = os.path.join(ROOT, "out", out_name)
    with open(out, "w") as fh:
        fh.write("% generated by code/render_tables_v9.py\n")
        fh.write("\\begin{tabular}{l r r r r r}\n\\hline\n")
        fh.write(
            "Dataset & $\\mu_{\\rm dj}$ & $\\mu_{\\rm open}$ & "
            "$\\mu_{\\rm closed}$ & $d_{\\rm closed{-}dj}$ & "
            "$d_{\\rm closed{-}open}$ \\\\\n\\hline\n"
        )
        for r in keep:
            fh.write(
                f"\\texttt{{{r['dataset']}}} & "
                f"{fmt_f(r['mean_dj'])} & {fmt_f(r['mean_open'])} & "
                f"{fmt_f(r['mean_tri'])} & "
                f"{fmt_f(r['d_dj_tri'], prec=2)} & "
                f"{fmt_f(r['d_open_tri'], prec=2)} \\\\\n"
            )
        fh.write("\\hline\n\\end{tabular}\n")
    print(f"Wrote {out}")


def write_size2_merged(rows, out_name):
    """Merged size-2 table: dj-vs-int columns plus three-class columns.
    Three-class cells are dashed for datasets that fail survives_three."""
    keep = [r for r in rows if survives_djns(r)]
    out = os.path.join(ROOT, "out", out_name)
    with open(out, "w") as fh:
        fh.write("% generated by code/render_tables_v9.py\n")
        fh.write("\\begin{tabular}{l r r r r r r r r r}\n\\hline\n")
        fh.write(
            "Dataset & $\\Delta$ & $E_{\\rm freq}$ & "
            "$\\mu_{\\rm dj}$ & $\\mu_{\\rm int}$ & $d$ & "
            "$\\mu_{\\rm open}$ & $\\mu_{\\rm closed}$ & "
            "$d_{\\rm open{-}dj}$ & $d_{\\rm closed{-}dj}$ "
            "\\\\\n\\hline\n"
        )
        for r in keep:
            three_ok = survives_three(r)
            o_mu = fmt_f(r['mean_open']) if three_ok else "--"
            c_mu = fmt_f(r['mean_tri']) if three_ok else "--"
            d_op = fmt_f(r['d_dj_open'], prec=2) if three_ok else "--"
            d_cl = fmt_f(r['d_dj_tri'], prec=2) if three_ok else "--"
            fh.write(
                f"\\texttt{{{r['dataset']}}} & {r['delta']} & "
                f"{fmt_int(r.get('E_freq', '0'))} & "
                f"{fmt_f(r['mean_dj'])} & {fmt_f(r['mean_ns'])} & "
                f"{fmt_f(r['d_dj_ns'], prec=2)} & "
                f"{o_mu} & {c_mu} & {d_op} & {d_cl} \\\\\n"
            )
        fh.write("\\hline\n\\end{tabular}\n")
    print(f"Wrote {out}")


def write_size2x3_merged(rows, out_name):
    """Merged size-2x3 (e-h3) table: dj-vs-int columns plus three-class.
    Three-class cells are dashed for datasets that fail survives_three."""
    keep = [r for r in rows if survives_djns(r)]
    out = os.path.join(ROOT, "out", out_name)
    with open(out, "w") as fh:
        fh.write("% generated by code/render_tables_v9.py\n")
        fh.write("\\begin{tabular}{l r r r r r r r}\n\\hline\n")
        fh.write(
            "Dataset & "
            "$\\mu_{\\rm dj}$ & $\\mu_{\\rm int}$ & $d$ & "
            "$\\mu_{\\rm open}$ & $\\mu_{\\rm closed}$ & "
            "$d_{\\rm open{-}dj}$ & $d_{\\rm closed{-}dj}$ "
            "\\\\\n\\hline\n"
        )
        for r in keep:
            three_ok = survives_three(r)
            o_mu = fmt_f(r['mean_open']) if three_ok else "--"
            c_mu = fmt_f(r['mean_tri']) if three_ok else "--"
            d_op = fmt_f(r['d_dj_open'], prec=2) if three_ok else "--"
            d_cl = fmt_f(r['d_dj_tri'], prec=2) if three_ok else "--"
            fh.write(
                f"\\texttt{{{r['dataset']}}} & "
                f"{fmt_f(r['mean_dj'])} & {fmt_f(r['mean_ns'])} & "
                f"{fmt_f(r['d_dj_ns'], prec=2)} & "
                f"{o_mu} & {c_mu} & {d_op} & {d_cl} \\\\\n"
            )
        fh.write("\\hline\n\\end{tabular}\n")
    print(f"Wrote {out}")


def write_3x3_main(rows, out_name):
    """3x3 main table: dj vs ns_1 vs ns_2.
    Cohen's $d$ columns are d(ns_1, dj) and d(ns_2, ns_1) per v14 spec."""
    keep = [r for r in rows if survives_3x3_main(r)]
    out = os.path.join(ROOT, "out", out_name)
    with open(out, "w") as fh:
        fh.write("% generated by code/render_tables_v9.py\n")
        fh.write("\\begin{tabular}{l r r r r r}\n\\hline\n")
        fh.write(
            "Dataset & "
            "$\\mu_{\\rm dj}$ & $\\mu_{{\\rm int}_1}$ & "
            "$\\mu_{{\\rm int}_2}$ & "
            "$d_{{{\\rm int}_1}{-}{\\rm dj}}$ & "
            "$d_{{{\\rm int}_2}{-}{{\\rm int}_1}}$ \\\\\n\\hline\n"
        )
        for r in keep:
            fh.write(
                f"\\texttt{{{r['dataset']}}} & "
                f"{fmt_f(r['mean_dj'])} & "
                f"{fmt_f(r['mean_ns1'])} & {fmt_f(r['mean_ns2'])} & "
                f"{fmt_f(r['d_ns1_dj'], prec=2)} & "
                f"{fmt_f(r['d_ns2_ns1'], prec=2)} \\\\\n"
            )
        fh.write("\\hline\n\\end{tabular}\n")
    print(f"Wrote {out}")


def write_3x3_fine(rows, out_name):
    """3x3 fine table: dj / ns_1_open / ns_1_tri / ns_2_open / ns_2_tri."""
    keep = [r for r in rows if survives_3x3_fine(r)]
    out = os.path.join(ROOT, "out", out_name)
    with open(out, "w") as fh:
        fh.write("% generated by code/render_tables_v9.py\n")
        fh.write("\\begin{tabular}{l r r r r r r r r r}\n\\hline\n")
        fh.write(
            "Dataset & "
            "$\\mu_{\\rm dj}$ & "
            "$\\mu_{{\\rm int}_1,{\\rm open}}$ & "
            "$\\mu_{{\\rm int}_1,{\\rm closed}}$ & "
            "$\\mu_{{\\rm int}_2,{\\rm open}}$ & "
            "$\\mu_{{\\rm int}_2,{\\rm closed}}$ & "
            "$d_{{{\\rm int}_1,{\\rm open}}{-}{\\rm dj}}$ & "
            "$d_{{{\\rm int}_1,{\\rm closed}}{-}{\\rm dj}}$ & "
            "$d_{{{\\rm int}_2,{\\rm open}}{-}{\\rm dj}}$ & "
            "$d_{{{\\rm int}_2,{\\rm closed}}{-}{\\rm dj}}$ \\\\\n\\hline\n"
        )
        for r in keep:
            fh.write(
                f"\\texttt{{{r['dataset']}}} & "
                f"{fmt_f(r['mean_dj'])} & "
                f"{fmt_f(r['mean_ns1_open'])} & "
                f"{fmt_f(r['mean_ns1_tri'])} & "
                f"{fmt_f(r['mean_ns2_open'])} & "
                f"{fmt_f(r['mean_ns2_tri'])} & "
                f"{fmt_f(r['d_ns1_open_dj'], prec=2)} & "
                f"{fmt_f(r['d_ns1_tri_dj'], prec=2)} & "
                f"{fmt_f(r['d_ns2_open_dj'], prec=2)} & "
                f"{fmt_f(r['d_ns2_tri_dj'], prec=2)} \\\\\n"
            )
        fh.write("\\hline\n\\end{tabular}\n")
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
